### ISSUE TITLE
from segraph import create_graph ImportError: cannot import name 'create_graph'

### ISSUE THREAD

**Issue by pinkfloyd06** [alivcor/segraph#3]
Hello,

l just installed segraph with both method (pip and wget ). It's installed correctly but when it comes tu run it, l got the following error :   
when l run  : 
`
from segraph import  * `

```
__init__.py", line 7, in <module>
    from segraph import create_graph
ImportError: cannot import name 'create_graph'
```

**Comment by alivcor** [comment]
Hi,

It seems to be working fine on my side. Please check again and provide more details

**Comment by pinkfloyd06** [comment]
It's the same. So l did the followig , execute it line by line : 

```
segments = slic(image, n_segments=500, sigma=1.0)
vertices = np.unique(segments_slic)
num_vertices = len(vertices)
mapping = dict(zip(vertices, np.arange(num_vertices)))
mapped_grid = np.array([mapping[x] for x in segments_slic.flat]).reshape(segments_slic.shape)
l2r = np.c_[mapped_grid[:, :-1].ravel(), mapped_grid[:, 1:].ravel()]
t2b = np.c_[mapped_grid[:-1, :].ravel(), mapped_grid[1:, :].ravel()]
edges = np.vstack([l2r, t2b])
edges = edges[edges[:, 0] != edges[:, 1], :]
edges = np.sort(edges, axis=1)
edge_map = edges[:, 0] + num_vertices * edges[:, 1]
edges = np.unique(edge_map)
```
until here it's awesome

but the last line reports errors : 
edges = [[vertices[edge % num_vertices],
          vertices[edge / num_vertices]] for edge in edges] 

which is : 

    **edges = [[vertices[edge % num_vertices],vertices[edge / num_vertices]] for edge in edges]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices**

**Comment by pinkfloyd06** [comment]
The problem is with casting, just use ` //` instead of `/` in `vertices[edge / num_vertices]`

**Comment by alivcor** [comment]
Great. Could you submit a Pull request for this. Seems like an issue.

**Comment by pinkfloyd06** [comment]
It's done
